[package]
name = "sm_motion_photo"
version = "0.1.0"
authors = ["vitaliy <vitaliy@velikodniy.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
boyer-moore-magiclen = "0.2.4"
mp4parse = "0.11.4"